name: deepgit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - nodejs>=18
  - pip:
    - flask
    - flask-cors
    - duckdb
    - google-generativeai
    - openai
    - fastapi
    - uvicorn
    - gunicorn
    - kaggle>=1.5.16
    - numpy
    - pandas
    - psutil
    - networkx
    - kuzu>=0.0.2
    - lxml>=4.9.0
    - requests>=2.25.0
    - langgraph>=0.2.0
    - langchain>=0.2.0
    - langchain-openai>=0.1.0
    - langchain-community>=0.2.0
    - langchain-google-genai>=0.1.0
    - python-dotenv>=1.0.0
    - matplotlib>=3.7.0 