name: Deploy to Render

on:
  push:
    branches:
      - retina  # Triggers on every commit to this branch
    paths-ignore:
      - '**.md' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [[ -z "$RENDER_DEPLOY_HOOK" ]]; then
            echo "Error: RENDER_DEPLOY_HOOK is not set."
            exit 1
          fi
          curl -X POST "$RENDER_DEPLOY_HOOK" || { echo "Render deployment trigger failed"; exit 1; }
