name: Deploy to Render

on:
  push:
    branches:
      - retina
    paths-ignore:
      - '**.md' 

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if curl -X POST "$RENDER_DEPLOY_HOOK"; then
            echo "Render deployment triggered successfully."
          else
            echo "Render deployment failed!" >&2
            exit 1
          fi