name: Deploy to Render

on:
  push:
    branches:
      - retina  # Change to your deployment branch

jobs:
  deploy-to-render:
    needs: build-and-push  # Ensure this runs only after the Docker image is pushed
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}